### PR TITLE
Updated baseUrl protocol to https

### PR DESCRIPTION
**Pull request by vestman**
(and removed some trailing whitespace)

### CODE REVIEW

**Comment by vestman** [comment]
Before the change:
```cURL error 28: Failed to connect to [app.rule.io](http://app.rule.io/) port 80: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 28: Failed to connect to [app.rule.io](http://app.rule.io/) port 80: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at /xxx/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200)"} []```

And according to your own [documentation](https://apidoc.rule.se/?_ga=2.171067872.1127132521.1628669630-1498802115.1628669630#header-encryption) it should be https. We changed it directly on the server and now it's working.

**Comment by Stan64** [comment]
Thanks, great find!

**Comment by vestman** [comment]
Will there be a new release with this fix included in the near future, @Stan64?

**Comment by Stan64** [comment]
@vestman Released just now!

**Pull request merged**
